apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dz87kh76r-nodejs 
  janus-idp.io/tekton: dz87kh76r-nodejs
  backstage.io/kubernetes-id: dz87kh76r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dz87kh76r-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml