apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dz87kh76r-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dz87kh76r-nodejs 
  name: dz87kh76r-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dz87kh76r-nodejs 
